language: cpp

sudo: false

compiler: gcc

branches:
  only: master

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - cd ../in
  - for i in *; do ../build/app/app "$i"; done
  - #for i in out*; do diff "$i" "../sampleout/$i"; done
  - cd ../build


after_success:
  - cd ../..
  - gcov src/*.cpp -o build/src/CMakeFiles/src.dir/
  - bash <(curl -s https://codecov.io/bash) -X gcov

notifications:
  email:
    on_success: change
    on_failure: change
