language: cpp

sudo: false

compiler: gcc

branches:
  only: master

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - cd app
  - for i in {1..5}; do echo "../../in/in$i.txt ../../in/out$i.txt" | ./app > /dev/null ; done
  - for i in {1..5}; do diff "../../sampleout/out$i.txt" "../../in/out$i.txt" ; done

notifications:
  email:
    on_success: change
    on_failure: change